### ISSUE TITLE
Smart Citizen doesn't show up

### ISSUE THREAD

**Issue by oscgonfer** [eosc-cos4cloud/mecoda-orange#49]
Due to the new changes on the Smart Citizen API, we get a `404` when getting the `kits` endpoint.

Traceback:
```
[2024-04-22 16:11:43] - [ERROR] API reported 404
Traceback (most recent call last):
  File "/home/xxxxxxx/mecoda_orange/smartcitizen_search.py", line 12, in <module>
    class SmartcitizenSearchWidget(OWBaseWidget):
  File "/home/xxxxxxx/mecoda-orange/mecoda_orange/smartcitizen_search.py", line 42, in SmartcitizenSearchWidget
    descriptive_blueprints = blueprints = ('', ) + tuple(sorted("{0:0=2d}".format(kit.id) + ': ' + kit.name for kit in blueprints),)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pynomaly** [comment]
This has been fixed on release 2.3.6. Thanks to @oscgonfer
